### ISSUE TITLE
NPM-friendly `package.json`s

### ISSUE THREAD

**Issue by bpmct** [coder/backstage-plugins#18]
Extracted from 

> @bpmct, Asher brought up some great points in [another ticket](https://github.com/coder/backstage-plugins/issues/4):
> 
> * [ ]  The readme title should probably match the package name?
> * [ ]  Seems NPM uses the first line in the readme as the description, but maybe we want an explicit description field in the package.json.
> * [ ]  Could add keywords in the package.json to make the plugins more discoverable.

Also happy to rename the title if I did it wrong!

**Comment by Kira-Pilot** [comment]
tracking in #34 so closing this issue
