### ISSUE TITLE
update Backstage READMEs

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/backstage-plugins#34]
Let's address the below feedback in our plugin README and general documentation:

- [x] Could we add a backstage logo or something to the README? It would help be a bit eye-catching.
- [x] Each plugin doesn't need to be prefixed with backstage-plugin-* since they are all in the Backstage repo. I think it'd be easier to read and understand if backstage-plugin-coder became: "Coder: Integrate Workspaces into your Backstage".
- [x] Does backstage-plugin-devcontainers-react need to have the -react suffix? Isn't all of Backstage in React? I think calling it -frontend would be better, since we have the -backend one. This is more of a question because I lack all context on Backstage, just a big naming nerd.
- [x]  On the specific plugin pages, I'd recommend we don't make the titles NPM package names. We want people to link these, and seeming too technical somewhat detracts from the value one could obtain IMO.
- [x] Seems NPM uses the first line in the readme as the description, but maybe we want an explicit description field in the package.json.
- [x]  Could add keywords in the package.json to make the plugins more discoverable.
- [x] "A collection of plugins that extend [Backstage](https://backstage.io/) to help with developer onboarding, context switching, and automated IDE environments (remote or local)." << let's fix this wording at the root README by removing 'environments' as it's already included in 'IDE'
- [x] Can we link our Discord as we do on coder core: [discord.gg/coder](http://discord.gg/coder)

**Comment by Parkreiner** [comment]
Just added a PR that addresses most of these. Not sure what @bpmct 's plans for Loom were (I could've sworn he mentioned recording some soon), but I'm going to look into the badges once I'm back from my lunch break

**Comment by Parkreiner** [comment]
Forgot to mention this about the badges, but I'd prefer for us to tighten up our test coverage a little more first before we have badges that show metrics and things like that

I don't think there would be any shame in adding them early – you could say that it's us being super-transparent, since we're not even on version 0.1.0 yet – but my personal preference would be to wait a little bit longer until we have a better baseline

**Comment by Parkreiner** [comment]
Going to turn the last two items into separate issues, but they should get done relatively quickly
Going to be working on tests today, and I'm going to finish up editing the main Coder plugin promo video tomorrow, which I think we can repurpose here. Then there would just be the Devcontainers plugin left
