### ISSUE TITLE
Coder plugin: integrate new query by workspace param functionality

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/backstage-plugins#60]
The Coder API now supports querying workspaces in a deployment by the set value of a `coder_parameter`. We should simplify our Backstage Coder plugin API layer by integrating this new functionality.

Blocked by https://github.com/coder/coder/issues/10661

**Comment by Parkreiner** [comment]
The new `CoderClient` PR is now pending, so I've started on this
I think I can have a basic implementation done today, but as I recall, there were some conversations about wanting to improve some of the search logic on Coder core's side. As I remember, the search only matches exactly, and can't do partial matches

Going to dig through some of the old Slack messages to refresh my memory, and then add some notes here

**Comment by code-asher** [comment]
One thing that comes to mind is maybe there is a case where a trailing slash is missing, and `https://github.com/owner/repo/` in the config does not match `https://github.com/owner/repo` in a workspace param.  Or maybe there is a case where one of them has the `/tree/branch` syntax and another does not?
