### ISSUE TITLE
Devcontainers plugins: review README

### ISSUE THREAD

**Issue by bpmct** [coder/backstage-plugins#63]
While installing the devcontainers plugins on a fresh Backstage deployment, I noticed several minor typos in code examples and snippets for the README. Sadly, I was rushing and did not take notes. Could we try installing the devcontainers plugins on a fresh backstage and making any edits to the README?

**Comment by Parkreiner** [comment]
Yeah, can definitely do a read-over, and verify that everything makes sense

**Comment by Parkreiner** [comment]
Update:
- Frontend plugin has had its code examples fleshed out a little more, and dealt with one typo in the example component's output
- The backend plugin is going to require a bit more work
   - I did not realize that the newest scaffolder gives you so little now, and a lot of the folders we have in our plugins repo don't exist on a fully-fresh installation
   - Roadie's directory looks incredibly similar to ours, which is throwing me off a bit
   - I'll figure out how to get the plugin set up with the new system tomorrow

**Comment by Parkreiner** [comment]
Another update:
- I'm actually having problems getting authenticated in GitHub from Backstage, and I'm not sure why
   - It seems like all the files in the fresh installation mirror our main repo
- I'll try looking into this a little more tomorrow morning, but if I still can't get it figured it out, I'll tag in Asher on Monday
